markdown: redcarpet
highlighter: pygments

title: "GDG Natal"
description: "Google Developer Group situado em Natal-RN Brasil"

permalink: /blog/:year/:month/:day/:title/
baseurl: ""

links:
  - title: Home
    url: /#home
  - title: Iniciativas
    url: /#iniciativas
  - title: Equipe
    url: /#equipe
  - title: Blog
    url: /Blog
  - title: Contato
    url: /#contato

url: "http://gdgnatal.com"
domain: "gdgnatal.com"

social:
  - desc: GOOGLE PLUS
    url: https://plus.google.com/+Gdgnatal-rn/ 
    title: Adicione no  google+
  - desc: GITHUB
    url:  https://github.com/gdg-natal
    title: Fork me on github
  - desc: FACEBOOK
    url:  https://facebook.com/gdgnatal
    title: Curta nossa página no Facebook
  - desc: GDG Natal Chapter
    url: https://developers.google.com/groups/chapter/111142392900301029730/
    title: Conheça nosso grupo

ga: UA-54337910-4

exclude: ['package.json', 'src', 'node_modules']
